### ISSUE TITLE
Enable option to run iperf3 directly instead of running docker container from cloudbandwidth

### ISSUE THREAD

**Issue by chintha-govardhan** [nerdalert/cloud-bandwidth#4]
As per the existing implementation, Cloud Bandwidth is creating docker containers to run iperf client for upload and download bandwidth tests. This will work well in docker environment, whereas for environments like kubernetes and different container technology this existing binary doesnt work as it is.

Proposing options to the script to support running iperf3 directly from system

**Comment by nerdalert** [comment]
This is insanely late, but I added this functionality to run the polling without a container runtime. Ty!

```shell
./cloud-bandwidth -config=config.yml -nocontainer -debug
INFO[0000] Running shell command ->  [-c iperf3 -P 1 -t 5 -f K -p 5201 -c 172.17.0.3 | tail -n 3 | head -n1 | awk '{print $7}']
```
